services:
  arpwatch:
    build:
      context: .
      dockerfile: Dockerfile
    image: arpwatch:latest
    network_mode: host
    env_file: .env
    volumes:
      - ./var-lib-arpwatch:/var/lib/arpwatch
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: false  # Use capabilities instead of full privileges
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  grafana-storage:
