global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'arpwatch_exporter'
    static_configs:
      - targets: ['arpwatch:8000']                              # Scrape exporter from arpwatch service :contentReference[oaicite:12]{index=12}
    metrics_path: /metrics
