global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'arpwatch_exporter'
    static_configs:
      - targets: ['localhost:8000']                            # Both services use host network mode :contentReference[oaicite:12]{index=12}
    metrics_path: /metrics
